version: 2
jobs:
  build-job:
    docker:
      - image: circleci/node:6.12
    working_directory: /tmp/gomashio
    steps:
      - checkout
      - run: mkdir /tmp/workspace
      - run: zip -r /tmp/workspace/index.zip .
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - index.zip

  deploy-job:
    docker:
      - image: circleci/node:6.12
        user: root
    working_directory: /tmp/gomashio
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: apt-get update && apt-get install -y awscli
      - run: aws s3 cp /tmp/workspace/index.zip s3://${S3_BUCKET_CODE_PIPELINE_SOURCE}/

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master
